@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 

@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 


@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 

@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7  --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 7 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 

@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 8 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 

@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 9 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 

@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 
@REM @REM .\.venv\Scripts\python.exe main.py --dst_folder_uuid --puzzles_dst_folder "data/thesis quantative results/" --number_sampled_points 10 --no_save_partitions_figures --sampling_img_path data/images/neom-Oj8w6hWC0dU-unsplash.jpg 




@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 12 --circle_num_ch 7 --circle_num_interior 0 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 5 --circle_num_ch 6 --circle_num_interior 1 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 9 --circle_num_ch 4 --circle_num_interior 3 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 9 --circle_num_ch 4 --circle_num_interior 3 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 50 --circle_num_ch 3 --circle_num_interior 4 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"

@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 14 --circle_num_ch 5 --circle_num_interior 3 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 3 --circle_num_ch 6 --circle_num_interior 3 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM .\.venv\Scripts\python.exe main.py --num_puzzles 50 --circle_num_ch 3 --circle_num_interior 2 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 47 --circle_num_ch 4 --circle_num_interior 2 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM @REM .\.venv\Scripts\python.exe main.py --num_puzzles 27 --circle_num_ch 6 --circle_num_interior 2 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM .\.venv\Scripts\python.exe main.py --num_puzzles 32 --circle_num_ch 7 --circle_num_interior 2 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"
@REM .\.venv\Scripts\python.exe main.py --num_puzzles 48 --circle_num_ch 8 --circle_num_interior 2 --circle_radius 7000 --dst_folder_uuid --postfix_dst_folder_uuid " on-circle" --no_save_partitions_figures --puzzles_dst_folder "data/thesis quantative results/"

@REM .\.venv\Scripts\python.exe main.py  --sampling-circle-num-ch 10 --sampling-circle-num-interior 0 --sampling-circle-radius 10000 --disable-saving-partitions-figures --dst-folder "data/thesis quantative results/"

@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 10 --sampling-img-num-points "9"  --sampling-img-path "data/paper/quantative_cardinality/canvas_100.png" --disable-saving-partitions-figures --dst-folder "data/paper/quantative_cardinality/9"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 10 --sampling-img-num-points "10"  --sampling-img-path "data/paper/quantative_cardinality/canvas_100.png" --disable-saving-partitions-figures --dst-folder "data/paper/quantative_cardinality/10"

@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 10  --sampling-circle-num-ch 10 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 9 --sampling-circle-num-interior 1 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 8 --sampling-circle-num-interior 2 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 7 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 6 --sampling-circle-num-interior 4 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 5 --sampling-circle-num-interior 5 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 4 --sampling-circle-num-interior 6 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 3 --sampling-circle-num-interior 7 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10"

@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 3 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 4 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 5 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 6 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 7 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 8 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 9 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5  --sampling-circle-num-ch 10 --sampling-circle-num-interior 0 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_no_interior"


@REM .\.venv\Scripts\python.exe main.py --dst-folder "data/paper/quantative_I_P_increase/10_debug/debug_2024-12-01 03-34-28+130709" --sampling-src-file "data/paper/quantative_I_P_increase/10/2024-12-01 03-34-28+130709/CH-3-INT-7-03-34-28.csv"


@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 9 --sampling-circle-num-interior 1 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 8 --sampling-circle-num-interior 2 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 7 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 6 --sampling-circle-num-interior 4 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 5 --sampling-circle-num-interior 5 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 4 --sampling-circle-num-interior 6 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 3 --sampling-circle-num-interior 7 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/10_second"

@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 6 --sampling-circle-num-interior 1 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/7"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 5 --sampling-circle-num-interior 2 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/7"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 4 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/7"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 3 --sampling-circle-num-interior 4 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/7"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 3 --sampling-circle-num-interior 4 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/7"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-img-num-points "7"  --sampling-img-path "data/paper/quantative_cardinality/canvas_100.png" --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/7"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 5 --sampling-circle-num-interior 1 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/6"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 4 --sampling-circle-num-interior 2 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/6"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 3 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/6"
@REM .\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 7 --sampling-circle-num-interior 1 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 6 --sampling-circle-num-interior 2 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 5 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 4 --sampling-circle-num-interior 4 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 3 --sampling-circle-num-interior 5 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 1000 --sampling-circle-num-ch 5 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 10 --sampling-img-num-points "8"  --sampling-img-path "data/paper/quantative_cardinality/canvas_100.png" --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/8"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 10 --sampling-img-num-points "9"  --sampling-img-path "data/paper/quantative_cardinality/canvas_100.png" --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/9"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 7 --sampling-circle-num-interior 2 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/9"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 8 --sampling-circle-num-interior 1 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/9"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 12000 --sampling-circle-num-ch 6 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/9"
.\.venv\Scripts\python.exe main.py --num-partitions-collections 5 --sampling-circle-radius 1000 --sampling-circle-num-ch 6 --sampling-circle-num-interior 3 --disable-saving-partitions-figures --dst-folder "data/paper/quantative_I_P_increase/9"